"""empty message

Revision ID: 82b7379be932
Revises: 70af16f4c9ac
Create Date: 2025-06-09 19:10:23.290773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b7379be932'
down_revision = '70af16f4c9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=255), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergens', sa.Text(), nullable=True))

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('saturated_fat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('sugars', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fiber', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('sodium', sa.Float(), nullable=False))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_grams', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('total_grams')
        batch_op.drop_column('portions')

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_column('sodium')
        batch_op.drop_column('salt')
        batch_op.drop_column('protein')
        batch_op.drop_column('fiber')
        batch_op.drop_column('sugars')
        batch_op.drop_column('carbs')
        batch_op.drop_column('saturated_fat')
        batch_op.drop_column('fat')
        batch_op.drop_column('calories')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('allergens')

    op.drop_table('shopping_list_items')
    # ### end Alembic commands ###
